<?php
namespace PHPPeru\Test\Exam;

use PHPPeru\Exam\SimpleExam;
use PHPPeru\Exam\SimpleStep;
use PHPPeru\Exam\Event\Events;
use PHPPeru\Test\Exam\TestCase;

/**
 * Test class for SimpleExam.
 * Generated by PHPUnit on 2012-03-09 at 21:22:33.
 */
class SimpleExamTest extends TestCase
{
    /**
     * @var SimpleExam
     */
    protected $exam;

    /**
     * @var SimpleStep Collection
     */
    protected $stepCollection = array();

    /**
     * @var Events
     */
    protected $triggeredEvents = array();

    /**
     * Sets up the exam to be used
     */
    protected function setUp()
    {
        $this->stepCollection[] = new SimpleStep('question 1');
        $this->stepCollection[] = new SimpleStep('question 2');

        $this->exam = new SimpleExam($this->stepCollection);
    }

    protected function tearDown()
    {
        unset($this->stepCollection);
        unset($this->exam);
    }

    /**
     * @covers PHPPeru\Exam\SimpleExam::start
     * @covers PHPPeru\Exam\SimpleExam::isStarted
     */
    public function testStart()
    {
        $this->exam->start();
        $this->assertTrue($this->exam->isStarted());
        $this->assertFalse($this->exam->isNew());
        $this->assertFalse($this->exam->isAborted());
        $this->assertFalse($this->exam->isCompleted());
    }

    /**
     * @covers PHPPeru\Exam\SimpleExam::abort
     * @covers PHPPeru\Exam\SimpleExam::isAborted
     */
    public function testAbort()
    {
        $this->exam->start();
        $this->exam->abort();
        $this->assertTrue($this->exam->isAborted());
        $this->assertFalse($this->exam->isNew());
        $this->assertFalse($this->exam->isStarted());
        $this->assertFalse($this->exam->isCompleted());
    }

    /**
     * @covers PHPPeru\Exam\SimpleExam::complete
     * @covers PHPPeru\Exam\SimpleExam::isCompleted
     */
    public function testComplete()
    {
        $this->exam->start();
        $this->exam->complete();
        $this->assertTrue($this->exam->isCompleted());
        $this->assertFalse($this->exam->isNew());
        $this->assertFalse($this->exam->isStarted());
        $this->assertFalse($this->exam->isAborted());
    }

    /**
     * Checks that newly created exams are marked as new 
     *
     * @covers PHPPeru\Exam\SimpleExam::isNew
     */
    public function testIsNew()
    {
        $this->assertTrue($this->exam->isNew());
        $this->assertFalse($this->exam->isStarted());
        $this->assertFalse($this->exam->isAborted());
        $this->assertFalse($this->exam->isCompleted());
    }

    /**
     * Checks that newly created exams have an associated event dispatcher 
     *
     * @covers PHPPeru\Exam\SimpleExam::isNew
     */
    public function testGetEventDispatcher()
    {
        $this->assertInstanceOf(
            'Symfony\Component\EventDispatcher\EventDispatcherInterface',
            $this->exam->getEventDispatcher()
        );
    }

    /**
     * Checks that events regarding the lifecycle are triggered correctly and
     * in the correct order when starting and completing an exam.
     */
    public function testEventsAreDispatchedDuringCompletedLifecycle()
    {
        $startListener = $this->getMock('stdClass', array('startCallback'));
        $startListener
            ->expects($this->once())
            ->method('startCallback')
            ->with($this->isInstanceOf('PHPPeru\Exam\Event'));
        $completeListener = $this->getMock('stdClass', array('completeCallback'));
        $completeListener
            ->expects($this->once())
            ->method('completeCallback')
            ->with($this->isInstanceOf('PHPPeru\Exam\Event'));
        $abortListener = $this->getMock('stdClass', array('abortCallback'));
        $abortListener
            ->expects($this->never())
            ->method('abortCallback');
        $evd = $this->exam->getEventDispatcher();
        $evd->addListener(
            Events::onStartExam,
            array($startListener, 'startCallback')
        );
        $evd->addListener(
            Events::onCompleteExam,
            array($completeListener, 'completeCallback')
        );
        $evd->addListener(
            Events::onAbortExam,
            array($abortListener, 'abortCallback')
        );
        $this->exam->start();
        $this->exam->complete();
    }

    /**
     * Checks that events regarding the lifecycle are triggered correctly and
     * in the correct order when starting and aborting an exam.
     */
    public function testEventsAreDispatchedDuringAbortedLifecycle()
    {
        $startListener = $this->getMock('stdClass', array('startCallback'));
        $startListener
            ->expects($this->once())
            ->method('startCallback')
            ->with($this->isInstanceOf('PHPPeru\Exam\Event'));
        $completeListener = $this->getMock('stdClass', array('completeCallback'));
        $completeListener
            ->expects($this->never())
            ->method('completeCallback');
        $abortListener = $this->getMock('stdClass', array('abortCallback'));
        $abortListener
            ->expects($this->once())
            ->method('abortCallback')
            ->with($this->isInstanceOf('PHPPeru\Exam\Event'));
        $evd = $this->exam->getEventDispatcher();
        $evd->addListener(
            Events::onStartExam,
            array($startListener, 'startCallback')
        );
        $evd->addListener(
            Events::onCompleteExam,
            array($completeListener, 'completeCallback')
        );
        $evd->addListener(
            Events::onAbortExam,
            array($abortListener, 'abortCallback')
        );
        $this->exam->start();
        $this->exam->abort();
    }

    /**
     * Checks that exception is thrown for when Exam cannot be started
     * @return mixed
     */
    public function testThrowBadMethodCallExceptionWhenExamCannotBeStarted()
    {
        $this->setExpectedException('BadMethodCallException');
        $this->exam->start();
        $this->exam->start();
    }

    /**
     * Checks that exception is thrown for when Exam cannot be completed
     * @return mixed
     */
    public function testThrowBadMethodCallExceptionWhenExamCannotBeCompleted()
    {
        $this->setExpectedException('BadMethodCallException');
        $this->exam->start();
        $this->exam->complete();
        $this->exam->complete();
    }

    /**
     * Checks that exception is thrown for when Exam cannot be aborted
     * @return mixed
     */
    public function testThrowBadMethodCallExceptionWhenExamCannotBeAborted()
    {
        $this->setExpectedException('BadMethodCallException');
        $this->exam->start();
        $this->exam->abort();
        $this->exam->abort();
    }

    public function testIteration()
    {
        $this->assertInstanceOf('Iterator', $this->exam, 'Exam is iterable.');
        $steps = array(
            $this->getMockExamStep(),
            $this->getMockExamStep(),
        );
        $this->exam->setSteps($steps);
        $this->assertEquals(0, $this->exam->key());
        $this->assertTrue($this->exam->valid());
        $this->assertSame($steps[0], $this->exam->current());
        $this->exam->next();
        $this->assertEquals(1, $this->exam->key());
        $this->assertSame($steps[1], $this->exam->current());
    }

    public function testIterator()
    {
        $steps = array(
            $this->getMockExamStep(),
            $this->getMockExamStep(),
        );
        $this->assertTrue(is_array($this->exam->getSteps()));
        $this->assertEquals(2, count($this->exam->getSteps()));
        $this->exam->setSteps($steps);
        $this->assertSame($steps, $this->exam->getSteps());
    }

    /**
     * Cannot evalute Exam without steps
     * @expectedException LogicException
     */
    public function testEvaluation()
    {
       $this->exam->getEvaluation();
    }

    private function getMockExamStep()
    {
        return $this->getMockBuilder('PHPPeru\Exam\SimpleStep')
            ->disableOriginalConstructor()
            ->getMock();
    }
}